name: Index

on:
  push:
    branches: ['main']
    paths:
      - 'content/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  update-index:
    name: Update Index
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_ORAMA_ENDPOINT: ${{ secrets.NEXT_PUBLIC_ORAMA_ENDPOINT }}
      NEXT_PUBLIC_ORAMA_API_KEY: ${{ secrets.NEXT_PUBLIC_ORAMA_API_KEY }}
      ORAMA_PRIVATE_INDEX: ${{ secrets.ORAMA_PRIVATE_INDEX }}
      ORAMA_PRIVATE_API_KEY: ${{ secrets.ORAMA_PRIVATE_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - run: yarn install --frozen-lockfile
      - name: Build app
        run: yarn build
      - name: Update index
        run: npx tsx scripts/sync-content.ts
